#This only works with the Plugin PurePerms!!
#
#Set the Groups and the Codes for it here
Owner:
  code: "ownerx6859430"
Admin:
  code: "adminx6584317"
Developer:
  code: "developerx776"



#This plugin is Licensed under Apache 2.0 License by supercrafter333!
#If you have questions or bugs, please open an Issue on Github:
#Or contact me on Discord: supercrafter333#4062

#I would be happy if you rate this plugin on Poggit:

#Have fun :)